// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalizedHealthcareTrackingSystemFinal.Data;

#nullable disable

namespace PersonalizedHealthcareTrackingSystemFinal.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251202084225_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.AppointmentModel", b =>
                {
                    b.Property<string>("AppointmentID")
                        .HasColumnType("text");

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChiefComplaint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VisitNumber")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentID = "appt-01",
                            AppointmentDateTime = new DateTime(2025, 12, 1, 17, 42, 24, 502, DateTimeKind.Utc).AddTicks(8859),
                            ChiefComplaint = "Sore throat and mild fever lasting 2 days.",
                            DoctorID = "doc-01",
                            Location = "Room 101",
                            Note = "",
                            PatientID = "pat-01",
                            Priority = 0,
                            Status = 2,
                            VisitNumber = 1
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.ClinicalExaminationModel", b =>
                {
                    b.Property<string>("ClinicalID")
                        .HasColumnType("text");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FamilyHistory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("LifestyleHabits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OxygenSaturation")
                        .HasColumnType("double precision");

                    b.Property<double>("Pulse")
                        .HasColumnType("double precision");

                    b.Property<string>("RecordID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RespiratoryRate")
                        .HasColumnType("double precision");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("ClinicalID");

                    b.HasIndex("RecordID")
                        .IsUnique();

                    b.ToTable("ClinicalExaminations");

                    b.HasData(
                        new
                        {
                            ClinicalID = "clin-01",
                            Allergies = "No known allergies.",
                            BloodPressure = "120/80",
                            FamilyHistory = "Father has hypertension.",
                            Height = 175.0,
                            LifestyleHabits = "Non-smoker.",
                            MedicalHistory = "None relevant.",
                            OxygenSaturation = 98.0,
                            Pulse = 85.0,
                            RecordID = "rec-01",
                            RespiratoryRate = 16.0,
                            Symptoms = "Throat pain, difficulty swallowing, low-grade fever.",
                            Temperature = 38.200000000000003,
                            Weight = 70.0
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.DoctorModel", b =>
                {
                    b.Property<string>("DoctorID")
                        .HasColumnType("text");

                    b.Property<double>("ConsultationFee")
                        .HasColumnType("double precision");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("DoctorID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorID = "doc-01",
                            ConsultationFee = 300000.0,
                            Rating = 4.7999999999999998,
                            Specialization = "General Practitioner",
                            UserID = "user-doc-01",
                            YearsOfExperience = 10
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.DoctorScheduleModel", b =>
                {
                    b.Property<string>("ScheduleID")
                        .HasColumnType("text");

                    b.Property<string>("DoctorID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScheduleID");

                    b.HasIndex("DoctorID");

                    b.ToTable("DoctorSchedules");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicalRecordModel", b =>
                {
                    b.Property<string>("RecordID")
                        .HasColumnType("text");

                    b.Property<string>("AppointmentID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NextVisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TreatmentPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VisitTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RecordID");

                    b.HasIndex("AppointmentID")
                        .IsUnique();

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            RecordID = "rec-01",
                            AppointmentID = "appt-01",
                            Diagnosis = "Acute Pharyngitis (Strep Throat)",
                            DoctorNotes = "Patient advised to finish full course of medication.",
                            NextVisitDate = new DateTime(2025, 12, 9, 8, 42, 24, 502, DateTimeKind.Utc).AddTicks(8893),
                            TreatmentPlan = "Antibiotics course and rest.",
                            VisitTime = new DateTime(2025, 12, 1, 17, 57, 24, 502, DateTimeKind.Utc).AddTicks(8892)
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationInteractionModel", b =>
                {
                    b.Property<string>("InteractionId")
                        .HasColumnType("text");

                    b.Property<string>("ClinicalEffects")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Management")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicationID1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicationID2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("InteractionId");

                    b.HasIndex("MedicationID1");

                    b.HasIndex("MedicationID2");

                    b.ToTable("MedicationInteractions");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationModel", b =>
                {
                    b.Property<string>("MedicationID")
                        .HasColumnType("text");

                    b.Property<int>("Form")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("SideEffect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("StockQuantityUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageInstruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MedicationID");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            MedicationID = "med-amox-500",
                            Form = 0,
                            Name = "Amoxicillin 500mg",
                            Price = 150000,
                            SideEffect = "Nausea, rash",
                            StockQuantity = 1000,
                            StockQuantityUnit = "box",
                            StorageInstruction = "Store at room temperature",
                            Unit = "mg"
                        },
                        new
                        {
                            MedicationID = "med-ibu-400",
                            Form = 0,
                            Name = "Ibuprofen 400mg",
                            Price = 80000,
                            SideEffect = "Stomach upset",
                            StockQuantity = 500,
                            StockQuantityUnit = "bottle",
                            StorageInstruction = "Keep dry",
                            Unit = "mg"
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationStockLogModel", b =>
                {
                    b.Property<string>("LogID")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedicationID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedPrescriptionID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LogID");

                    b.HasIndex("MedicationID");

                    b.HasIndex("RelatedPrescriptionID");

                    b.ToTable("MedicationStockLogs");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PatientModel", b =>
                {
                    b.Property<string>("PatientID")
                        .HasColumnType("text");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("InsuranceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PatientID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientID = "pat-01",
                            BloodType = "A+",
                            DateOfBirth = new DateTime(1985, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gender = 0,
                            InsuranceNumber = "INS-123456",
                            UserID = "user-pat-01"
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PharmacistModel", b =>
                {
                    b.Property<string>("PharmacistID")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PharmacistID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Pharmacists");

                    b.HasData(
                        new
                        {
                            PharmacistID = "phar-01",
                            Department = "Main Dispensary",
                            UserID = "user-phar-01"
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PrescriptionItemModel", b =>
                {
                    b.Property<string>("ItemID")
                        .HasColumnType("text");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoseScheduleJSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Indication")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicationID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrescriptionID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ItemID");

                    b.HasIndex("MedicationID");

                    b.HasIndex("PrescriptionID");

                    b.ToTable("PrescriptionItems");

                    b.HasData(
                        new
                        {
                            ItemID = "pi-01",
                            Dosage = "500mg",
                            DoseScheduleJSON = "{\"morning\": 1, \"afternoon\": 1, \"evening\": 1}",
                            DurationDays = 7,
                            Frequency = "3 times a day (every 8 hours)",
                            Indication = "For bacterial infection.",
                            Instruction = "Take after meals.",
                            MedicationID = "med-amox-500",
                            PrescriptionID = "presc-01",
                            Quantity = 21
                        },
                        new
                        {
                            ItemID = "pi-02",
                            Dosage = "400mg",
                            DoseScheduleJSON = "{\"as_needed\": true}",
                            DurationDays = 5,
                            Frequency = "As needed for pain/fever, max 3 times daily",
                            Indication = "For pain and fever management.",
                            Instruction = "Do not take on an empty stomach.",
                            MedicationID = "med-ibu-400",
                            PrescriptionID = "presc-01",
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PrescriptionModel", b =>
                {
                    b.Property<string>("PrescriptionID")
                        .HasColumnType("text");

                    b.Property<DateTime>("DispensedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PharmacistID")
                        .HasColumnType("text");

                    b.Property<DateTime>("PrescriptionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RecordID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PrescriptionID");

                    b.HasIndex("PharmacistID");

                    b.HasIndex("RecordID")
                        .IsUnique();

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            PrescriptionID = "presc-01",
                            DispensedAt = new DateTime(2025, 12, 2, 8, 42, 24, 502, DateTimeKind.Utc).AddTicks(8941),
                            PrescriptionDateTime = new DateTime(2025, 12, 1, 18, 12, 24, 502, DateTimeKind.Utc).AddTicks(8939),
                            Priority = 0,
                            RecordID = "rec-01",
                            Status = 0,
                            VerifiedAt = new DateTime(2025, 12, 2, 8, 42, 24, 502, DateTimeKind.Utc).AddTicks(8940)
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.UserModel", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = "user-pat-01",
                            Email = "john@example.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            PasswordHash = "Password123!",
                            PhoneNumber = "0901234567",
                            Role = 0,
                            Username = "john.doe"
                        },
                        new
                        {
                            UserID = "user-doc-01",
                            Email = "sarah.smith@clinic.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Smith",
                            PasswordHash = "Password123!",
                            PhoneNumber = "0909998887",
                            Role = 1,
                            Username = "dr.sarah"
                        },
                        new
                        {
                            UserID = "user-phar-01",
                            Email = "david.chen@pharmacy.com",
                            FirstName = "David",
                            IsActive = true,
                            LastName = "Chen",
                            PasswordHash = "Password123!",
                            PhoneNumber = "0905554443",
                            Role = 2,
                            Username = "phar.david"
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.AppointmentModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.DoctorModel", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.PatientModel", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.ClinicalExaminationModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.MedicalRecordModel", "MedicalRecord")
                        .WithOne("ClinicalExamination")
                        .HasForeignKey("PersonalizedHealthcareTrackingSystemFinal.Models.ClinicalExaminationModel", "RecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.DoctorModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.UserModel", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("PersonalizedHealthcareTrackingSystemFinal.Models.DoctorModel", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.DoctorScheduleModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.DoctorModel", "Doctor")
                        .WithMany("DoctorSchedules")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicalRecordModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.AppointmentModel", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("PersonalizedHealthcareTrackingSystemFinal.Models.MedicalRecordModel", "AppointmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationInteractionModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationModel", "Medication1")
                        .WithMany("MedicationInteractions1")
                        .HasForeignKey("MedicationID1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationModel", "Medication2")
                        .WithMany("MedicationInteractions2")
                        .HasForeignKey("MedicationID2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medication1");

                    b.Navigation("Medication2");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationStockLogModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationModel", "Medication")
                        .WithMany("MedicationStockLogs")
                        .HasForeignKey("MedicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.PrescriptionModel", "Prescription")
                        .WithMany("MedicationStockLogs")
                        .HasForeignKey("RelatedPrescriptionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PatientModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.UserModel", "User")
                        .WithOne("Patient")
                        .HasForeignKey("PersonalizedHealthcareTrackingSystemFinal.Models.PatientModel", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PharmacistModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.UserModel", "User")
                        .WithOne("Pharmacist")
                        .HasForeignKey("PersonalizedHealthcareTrackingSystemFinal.Models.PharmacistModel", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PrescriptionItemModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationModel", "Medication")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("MedicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.PrescriptionModel", "Prescription")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("PrescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PrescriptionModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.PharmacistModel", "PharmacistChecking")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PharmacistID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.MedicalRecordModel", "MedicalRecord")
                        .WithOne("Prescription")
                        .HasForeignKey("PersonalizedHealthcareTrackingSystemFinal.Models.PrescriptionModel", "RecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");

                    b.Navigation("PharmacistChecking");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.AppointmentModel", b =>
                {
                    b.Navigation("MedicalRecord")
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.DoctorModel", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorSchedules");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicalRecordModel", b =>
                {
                    b.Navigation("ClinicalExamination")
                        .IsRequired();

                    b.Navigation("Prescription")
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationModel", b =>
                {
                    b.Navigation("MedicationInteractions1");

                    b.Navigation("MedicationInteractions2");

                    b.Navigation("MedicationStockLogs");

                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PatientModel", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PharmacistModel", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PrescriptionModel", b =>
                {
                    b.Navigation("MedicationStockLogs");

                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.UserModel", b =>
                {
                    b.Navigation("Doctor")
                        .IsRequired();

                    b.Navigation("Patient")
                        .IsRequired();

                    b.Navigation("Pharmacist")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
