// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalizedHealthcareTrackingSystemFinal.Data;

#nullable disable

namespace PersonalizedHealthcareTrackingSystemFinal.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.AppointmentModel", b =>
                {
                    b.Property<string>("AppointmentID")
                        .HasColumnType("text");

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChiefComplaint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VisitNumber")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentID = "appt-01",
                            AppointmentDateTime = new DateTime(2025, 12, 5, 19, 6, 37, 939, DateTimeKind.Utc).AddTicks(8951),
                            ChiefComplaint = "Sore throat and mild fever lasting 2 days.",
                            DoctorID = "doc-01",
                            Location = "Room 101",
                            Note = "",
                            PatientID = "pat-01",
                            Priority = 0,
                            Status = 2,
                            VisitNumber = 1
                        },
                        new
                        {
                            AppointmentID = "appt-02",
                            AppointmentDateTime = new DateTime(2025, 12, 5, 0, 6, 37, 939, DateTimeKind.Utc).AddTicks(8962),
                            ChiefComplaint = "Regular checkup for hypertension.",
                            DoctorID = "doc-02",
                            Location = "Room 205",
                            Note = "",
                            PatientID = "pat-02",
                            Priority = 0,
                            Status = 2,
                            VisitNumber = 1
                        },
                        new
                        {
                            AppointmentID = "appt-03",
                            AppointmentDateTime = new DateTime(2025, 12, 1, 20, 6, 37, 939, DateTimeKind.Utc).AddTicks(8964),
                            ChiefComplaint = "Chest pain after exercise.",
                            DoctorID = "doc-02",
                            Location = "Room 205",
                            Note = "",
                            PatientID = "pat-03",
                            Priority = 1,
                            Status = 2,
                            VisitNumber = 1
                        },
                        new
                        {
                            AppointmentID = "appt-04",
                            AppointmentDateTime = new DateTime(2025, 12, 7, 19, 6, 37, 939, DateTimeKind.Utc).AddTicks(8966),
                            ChiefComplaint = "Vaccination schedule.",
                            DoctorID = "doc-01",
                            Location = "Room 102",
                            Note = "",
                            PatientID = "pat-04",
                            Priority = 0,
                            Status = 0,
                            VisitNumber = 1
                        },
                        new
                        {
                            AppointmentID = "appt-05",
                            AppointmentDateTime = new DateTime(2025, 11, 27, 0, 6, 37, 939, DateTimeKind.Utc).AddTicks(8969),
                            ChiefComplaint = "Unexplained leg pain.",
                            DoctorID = "doc-03",
                            Location = "Room 303",
                            Note = "",
                            PatientID = "pat-01",
                            Priority = 2,
                            Status = 2,
                            VisitNumber = 2
                        },
                        new
                        {
                            AppointmentID = "appt-06",
                            AppointmentDateTime = new DateTime(2025, 12, 6, 12, 6, 37, 939, DateTimeKind.Utc).AddTicks(8971),
                            ChiefComplaint = "Follow up on surgical scar.",
                            DoctorID = "doc-04",
                            Location = "Room 401",
                            Note = "",
                            PatientID = "pat-02",
                            Priority = 0,
                            Status = 0,
                            VisitNumber = 2
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.ClinicalExaminationModel", b =>
                {
                    b.Property<string>("ClinicalID")
                        .HasColumnType("text");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FamilyHistory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("LifestyleHabits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OxygenSaturation")
                        .HasColumnType("double precision");

                    b.Property<double>("Pulse")
                        .HasColumnType("double precision");

                    b.Property<string>("RecordID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RespiratoryRate")
                        .HasColumnType("double precision");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("ClinicalID");

                    b.HasIndex("RecordID")
                        .IsUnique();

                    b.ToTable("ClinicalExaminations");

                    b.HasData(
                        new
                        {
                            ClinicalID = "clin-01",
                            Allergies = "No known allergies.",
                            BloodPressure = "120/80",
                            FamilyHistory = "Father has hypertension.",
                            Height = 175.0,
                            LifestyleHabits = "Non-smoker.",
                            MedicalHistory = "None relevant.",
                            OxygenSaturation = 98.0,
                            Pulse = 85.0,
                            RecordID = "rec-01",
                            RespiratoryRate = 16.0,
                            Symptoms = "Throat pain, difficulty swallowing, low-grade fever.",
                            Temperature = 38.200000000000003,
                            Weight = 70.0
                        },
                        new
                        {
                            ClinicalID = "clin-02",
                            Allergies = "Penicillin.",
                            BloodPressure = "145/95",
                            FamilyHistory = "Mother has diabetes.",
                            Height = 162.0,
                            LifestyleHabits = "Sedentary lifestyle.",
                            MedicalHistory = "Diagnosed with hypertension 2 years ago.",
                            OxygenSaturation = 99.0,
                            Pulse = 78.0,
                            RecordID = "rec-02",
                            RespiratoryRate = 18.0,
                            Symptoms = "Occasional headaches, dizziness.",
                            Temperature = 36.799999999999997,
                            Weight = 65.0
                        },
                        new
                        {
                            ClinicalID = "clin-03",
                            Allergies = "None.",
                            BloodPressure = "150/95",
                            FamilyHistory = "Brother died of MI at 50.",
                            Height = 198.0,
                            LifestyleHabits = "Social smoker.",
                            MedicalHistory = "High cholesterol.",
                            OxygenSaturation = 96.0,
                            Pulse = 92.0,
                            RecordID = "rec-03",
                            RespiratoryRate = 20.0,
                            Symptoms = "Tightness in chest, shortness of breath on exertion.",
                            Temperature = 37.0,
                            Weight = 100.0
                        },
                        new
                        {
                            ClinicalID = "clin-04",
                            Allergies = "Latex.",
                            BloodPressure = "130/85",
                            FamilyHistory = "Unknown.",
                            Height = 180.0,
                            LifestyleHabits = "Active.",
                            MedicalHistory = "Recent long-haul flight.",
                            OxygenSaturation = 98.0,
                            Pulse = 88.0,
                            RecordID = "rec-04",
                            RespiratoryRate = 18.0,
                            Symptoms = "Swelling in right calf, warm to touch.",
                            Temperature = 37.5,
                            Weight = 80.0
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.DoctorModel", b =>
                {
                    b.Property<string>("DoctorID")
                        .HasColumnType("text");

                    b.Property<double>("ConsultationFee")
                        .HasColumnType("double precision");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("DoctorID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorID = "doc-01",
                            ConsultationFee = 300000.0,
                            Rating = 4.7999999999999998,
                            Specialization = "General Practitioner",
                            UserID = "user-doc-01",
                            YearsOfExperience = 10
                        },
                        new
                        {
                            DoctorID = "doc-02",
                            ConsultationFee = 500000.0,
                            Rating = 4.9000000000000004,
                            Specialization = "Cardiologist",
                            UserID = "user-doc-02",
                            YearsOfExperience = 15
                        },
                        new
                        {
                            DoctorID = "doc-03",
                            ConsultationFee = 1000000.0,
                            Rating = 3.5,
                            Specialization = "Diagnostician",
                            UserID = "user-doc-03",
                            YearsOfExperience = 20
                        },
                        new
                        {
                            DoctorID = "doc-04",
                            ConsultationFee = 600000.0,
                            Rating = 4.9000000000000004,
                            Specialization = "General Surgery",
                            UserID = "user-doc-04",
                            YearsOfExperience = 8
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.DoctorScheduleModel", b =>
                {
                    b.Property<string>("ScheduleID")
                        .HasColumnType("text");

                    b.Property<string>("DoctorID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScheduleID");

                    b.HasIndex("DoctorID");

                    b.ToTable("DoctorSchedules");

                    b.HasData(
                        new
                        {
                            ScheduleID = "sch-01",
                            DoctorID = "doc-01",
                            EndTime = new DateTime(2025, 12, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 12, 5, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ScheduleID = "sch-02",
                            DoctorID = "doc-01",
                            EndTime = new DateTime(2025, 12, 7, 17, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 12, 7, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ScheduleID = "sch-03",
                            DoctorID = "doc-02",
                            EndTime = new DateTime(2025, 12, 4, 21, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 12, 4, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ScheduleID = "sch-04",
                            DoctorID = "doc-02",
                            EndTime = new DateTime(2025, 12, 1, 16, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 12, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ScheduleID = "sch-05",
                            DoctorID = "doc-03",
                            EndTime = new DateTime(2025, 11, 26, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 11, 26, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ScheduleID = "sch-06",
                            DoctorID = "doc-04",
                            EndTime = new DateTime(2025, 12, 6, 19, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 12, 6, 7, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ScheduleID = "sch-07",
                            DoctorID = "doc-03",
                            EndTime = new DateTime(2025, 12, 8, 17, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 12, 8, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ScheduleID = "sch-08",
                            DoctorID = "doc-04",
                            EndTime = new DateTime(2025, 12, 9, 16, 0, 0, 0, DateTimeKind.Utc),
                            StartTime = new DateTime(2025, 12, 9, 8, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicalRecordModel", b =>
                {
                    b.Property<string>("RecordID")
                        .HasColumnType("text");

                    b.Property<string>("AppointmentID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NextVisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TreatmentPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VisitTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RecordID");

                    b.HasIndex("AppointmentID")
                        .IsUnique();

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            RecordID = "rec-01",
                            AppointmentID = "appt-01",
                            Diagnosis = "Acute Pharyngitis (Strep Throat)",
                            DoctorNotes = "Patient advised to finish full course of medication.",
                            NextVisitDate = new DateTime(2025, 12, 13, 10, 6, 37, 939, DateTimeKind.Utc).AddTicks(9018),
                            TreatmentPlan = "Antibiotics course and rest.",
                            VisitTime = new DateTime(2025, 12, 5, 19, 21, 37, 939, DateTimeKind.Utc).AddTicks(9015)
                        },
                        new
                        {
                            RecordID = "rec-02",
                            AppointmentID = "appt-02",
                            Diagnosis = "Essential Hypertension",
                            DoctorNotes = "BP slightly elevated. Monitoring required.",
                            NextVisitDate = new DateTime(2026, 1, 6, 10, 6, 37, 939, DateTimeKind.Utc).AddTicks(9021),
                            TreatmentPlan = "Lifestyle modification and daily medication.",
                            VisitTime = new DateTime(2025, 12, 5, 0, 36, 37, 939, DateTimeKind.Utc).AddTicks(9020)
                        },
                        new
                        {
                            RecordID = "rec-03",
                            AppointmentID = "appt-03",
                            Diagnosis = "Stable Angina",
                            DoctorNotes = "Patient needs to monitor heart rate.",
                            NextVisitDate = new DateTime(2025, 12, 20, 10, 6, 37, 939, DateTimeKind.Utc).AddTicks(9028),
                            TreatmentPlan = "Prescribed statins and nitroglycerin. Cardiac stress test ordered.",
                            VisitTime = new DateTime(2025, 12, 1, 20, 36, 37, 939, DateTimeKind.Utc).AddTicks(9027)
                        },
                        new
                        {
                            RecordID = "rec-04",
                            AppointmentID = "appt-05",
                            Diagnosis = "Deep Vein Thrombosis (DVT)",
                            DoctorNotes = "Confirmed via Ultrasound.",
                            NextVisitDate = new DateTime(2025, 12, 9, 10, 6, 37, 939, DateTimeKind.Utc).AddTicks(9030),
                            TreatmentPlan = "Anticoagulant therapy immediately.",
                            VisitTime = new DateTime(2025, 11, 27, 1, 6, 37, 939, DateTimeKind.Utc).AddTicks(9029)
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationInteractionModel", b =>
                {
                    b.Property<string>("InteractionID")
                        .HasColumnType("text");

                    b.Property<string>("ClinicalEffects")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Management")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Medication1ID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Medication2ID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("InteractionID");

                    b.HasIndex("Medication1ID");

                    b.HasIndex("Medication2ID");

                    b.ToTable("MedicationInteractions");

                    b.HasData(
                        new
                        {
                            InteractionID = "int-01",
                            ClinicalEffects = "NSAIDs may impair renal function, increasing the risk of metformin-associated lactic acidosis.",
                            Description = "Potential reduction in renal function.",
                            Management = "Monitor renal function periodically.",
                            Medication1ID = "med-ibu-400",
                            Medication2ID = "med-met-850",
                            Severity = 1
                        },
                        new
                        {
                            InteractionID = "int-02",
                            ClinicalEffects = "Omeprazole may slightly increase the serum concentration of Atorvastatin.",
                            Description = "Altered absorption.",
                            Management = "Monitor for statin-related side effects like muscle pain.",
                            Medication1ID = "med-ator-20",
                            Medication2ID = "med-omep-20",
                            Severity = 0
                        },
                        new
                        {
                            InteractionID = "int-03",
                            ClinicalEffects = "NSAIDs may reduce the cardiovascular protection of statins in high risk patients.",
                            Description = "Potential reduced antihypertensive effect.",
                            Management = "Use lowest effective dose of NSAID.",
                            Medication1ID = "med-ibu-400",
                            Medication2ID = "med-ator-20",
                            Severity = 0
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationModel", b =>
                {
                    b.Property<string>("MedicationID")
                        .HasColumnType("text");

                    b.Property<int>("Form")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("SideEffect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("StockQuantityUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageInstruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MedicationID");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            MedicationID = "med-amox-500",
                            Form = 0,
                            Name = "Amoxicillin 500mg",
                            Price = 150000,
                            SideEffect = "Nausea, rash",
                            StockQuantity = 1000,
                            StockQuantityUnit = "box",
                            StorageInstruction = "Store at room temperature",
                            Unit = "mg"
                        },
                        new
                        {
                            MedicationID = "med-ibu-400",
                            Form = 0,
                            Name = "Ibuprofen 400mg",
                            Price = 80000,
                            SideEffect = "Stomach upset",
                            StockQuantity = 500,
                            StockQuantityUnit = "bottle",
                            StorageInstruction = "Keep dry",
                            Unit = "mg"
                        },
                        new
                        {
                            MedicationID = "med-para-500",
                            Form = 0,
                            Name = "Paracetamol 500mg",
                            Price = 50000,
                            SideEffect = "Liver toxicity (high dose)",
                            StockQuantity = 2000,
                            StockQuantityUnit = "box",
                            StorageInstruction = "Store in cool place",
                            Unit = "mg"
                        },
                        new
                        {
                            MedicationID = "med-met-850",
                            Form = 0,
                            Name = "Metformin 850mg",
                            Price = 120000,
                            SideEffect = "Nausea, gastrointestinal disturbance",
                            StockQuantity = 800,
                            StockQuantityUnit = "box",
                            StorageInstruction = "Store at room temperature",
                            Unit = "mg"
                        },
                        new
                        {
                            MedicationID = "med-cet-10",
                            Form = 0,
                            Name = "Cetirizine 10mg",
                            Price = 45000,
                            SideEffect = "Drowsiness, dry mouth",
                            StockQuantity = 2000,
                            StockQuantityUnit = "blister",
                            StorageInstruction = "Store in dry place",
                            Unit = "mg"
                        },
                        new
                        {
                            MedicationID = "med-ator-20",
                            Form = 0,
                            Name = "Atorvastatin 20mg",
                            Price = 180000,
                            SideEffect = "Muscle pain, digestive issues",
                            StockQuantity = 800,
                            StockQuantityUnit = "box",
                            StorageInstruction = "Store at room temperature",
                            Unit = "mg"
                        },
                        new
                        {
                            MedicationID = "med-omep-20",
                            Form = 1,
                            Name = "Omeprazole 20mg",
                            Price = 95000,
                            SideEffect = "Headache, nausea",
                            StockQuantity = 1200,
                            StockQuantityUnit = "bottle",
                            StorageInstruction = "Keep away from light",
                            Unit = "mg"
                        },
                        new
                        {
                            MedicationID = "med-salb-inhaler",
                            Form = 6,
                            Name = "Salbutamol Inhaler",
                            Price = 110000,
                            SideEffect = "Tremors, nervousness",
                            StockQuantity = 300,
                            StockQuantityUnit = "canister",
                            StorageInstruction = "Store below 30°C",
                            Unit = "mcg"
                        },
                        new
                        {
                            MedicationID = "med-vit-c-500",
                            Form = 0,
                            Name = "Vitamin C 500mg",
                            Price = 60000,
                            SideEffect = "Stomach cramps (high dose)",
                            StockQuantity = 5000,
                            StockQuantityUnit = "bottle",
                            StorageInstruction = "Keep tightly closed",
                            Unit = "mg"
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationStockLogModel", b =>
                {
                    b.Property<string>("LogID")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedicationID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedPrescriptionID")
                        .HasColumnType("text");

                    b.HasKey("LogID");

                    b.HasIndex("MedicationID");

                    b.HasIndex("RelatedPrescriptionID");

                    b.ToTable("MedicationStockLogs");

                    b.HasData(
                        new
                        {
                            LogID = "log-01",
                            CreatedAt = new DateTime(2025, 11, 6, 10, 6, 37, 939, DateTimeKind.Utc).AddTicks(9287),
                            MedicationID = "med-amox-500",
                            QuantityChange = 1000,
                            Reason = "Initial Stock Import"
                        },
                        new
                        {
                            LogID = "log-02",
                            CreatedAt = new DateTime(2025, 11, 6, 10, 6, 37, 939, DateTimeKind.Utc).AddTicks(9289),
                            MedicationID = "med-ibu-400",
                            QuantityChange = 500,
                            Reason = "Initial Stock Import"
                        },
                        new
                        {
                            LogID = "log-03",
                            CreatedAt = new DateTime(2025, 12, 5, 19, 51, 37, 939, DateTimeKind.Utc).AddTicks(9291),
                            MedicationID = "med-amox-500",
                            QuantityChange = -21,
                            Reason = "Dispensed to Patient",
                            RelatedPrescriptionID = "presc-01"
                        },
                        new
                        {
                            LogID = "log-04",
                            CreatedAt = new DateTime(2025, 12, 5, 19, 51, 37, 939, DateTimeKind.Utc).AddTicks(9294),
                            MedicationID = "med-ibu-400",
                            QuantityChange = -10,
                            Reason = "Dispensed to Patient",
                            RelatedPrescriptionID = "presc-01"
                        },
                        new
                        {
                            LogID = "log-05",
                            CreatedAt = new DateTime(2025, 12, 5, 1, 51, 37, 939, DateTimeKind.Utc).AddTicks(9296),
                            MedicationID = "med-met-850",
                            QuantityChange = -60,
                            Reason = "Dispensed to Patient",
                            RelatedPrescriptionID = "presc-02"
                        },
                        new
                        {
                            LogID = "log-06",
                            CreatedAt = new DateTime(2025, 12, 1, 21, 36, 37, 939, DateTimeKind.Utc).AddTicks(9298),
                            MedicationID = "med-ator-20",
                            QuantityChange = -30,
                            Reason = "Dispensed to Patient",
                            RelatedPrescriptionID = "presc-03"
                        },
                        new
                        {
                            LogID = "log-07",
                            CreatedAt = new DateTime(2025, 12, 1, 21, 36, 37, 939, DateTimeKind.Utc).AddTicks(9300),
                            MedicationID = "med-omep-20",
                            QuantityChange = -14,
                            Reason = "Dispensed to Patient",
                            RelatedPrescriptionID = "presc-03"
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PatientModel", b =>
                {
                    b.Property<string>("PatientID")
                        .HasColumnType("text");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("InsuranceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PatientID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientID = "pat-01",
                            BloodType = "A+",
                            DateOfBirth = new DateTime(1985, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gender = 0,
                            InsuranceNumber = "INS-123456",
                            UserID = "user-pat-01"
                        },
                        new
                        {
                            PatientID = "pat-02",
                            BloodType = "O-",
                            DateOfBirth = new DateTime(1990, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gender = 1,
                            InsuranceNumber = "INS-987654",
                            UserID = "user-pat-02"
                        },
                        new
                        {
                            PatientID = "pat-03",
                            BloodType = "AB-",
                            DateOfBirth = new DateTime(1975, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gender = 0,
                            InsuranceNumber = "INS-555666",
                            UserID = "user-pat-03"
                        },
                        new
                        {
                            PatientID = "pat-04",
                            BloodType = "B+",
                            DateOfBirth = new DateTime(2015, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gender = 1,
                            InsuranceNumber = "INS-CHILD-01",
                            UserID = "user-pat-04"
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PharmacistModel", b =>
                {
                    b.Property<string>("PharmacistID")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PharmacistID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Pharmacists");

                    b.HasData(
                        new
                        {
                            PharmacistID = "phar-01",
                            Department = "Main Dispensary",
                            UserID = "user-phar-01"
                        },
                        new
                        {
                            PharmacistID = "phar-02",
                            Department = "Inpatient Pharmacy",
                            UserID = "user-phar-02"
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PrescriptionItemModel", b =>
                {
                    b.Property<string>("ItemID")
                        .HasColumnType("text");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoseScheduleJSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Indication")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicationID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrescriptionID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ItemID");

                    b.HasIndex("MedicationID");

                    b.HasIndex("PrescriptionID");

                    b.ToTable("PrescriptionItems");

                    b.HasData(
                        new
                        {
                            ItemID = "pi-01",
                            Dosage = "500mg",
                            DoseScheduleJSON = "{\"morning\": 1, \"afternoon\": 1, \"evening\": 1}",
                            DurationDays = 7,
                            Frequency = "3 times a day (every 8 hours)",
                            Indication = "For bacterial infection.",
                            Instruction = "Take after meals.",
                            MedicationID = "med-amox-500",
                            PrescriptionID = "presc-01",
                            Quantity = 21
                        },
                        new
                        {
                            ItemID = "pi-02",
                            Dosage = "400mg",
                            DoseScheduleJSON = "{\"as_needed\": true}",
                            DurationDays = 5,
                            Frequency = "As needed for pain/fever, max 3 times daily",
                            Indication = "For pain and fever management.",
                            Instruction = "Do not take on an empty stomach.",
                            MedicationID = "med-ibu-400",
                            PrescriptionID = "presc-01",
                            Quantity = 10
                        },
                        new
                        {
                            ItemID = "pi-03",
                            Dosage = "850mg",
                            DoseScheduleJSON = "{\"morning\": 1, \"evening\": 1}",
                            DurationDays = 30,
                            Frequency = "Twice a day",
                            Indication = "Diabetes management.",
                            Instruction = "Take with meals to reduce stomach upset.",
                            MedicationID = "med-met-850",
                            PrescriptionID = "presc-02",
                            Quantity = 60
                        },
                        new
                        {
                            ItemID = "pi-04",
                            Dosage = "20mg",
                            DoseScheduleJSON = "{\"night\": 1}",
                            DurationDays = 30,
                            Frequency = "Once daily at night",
                            Indication = "Cholesterol management.",
                            Instruction = "Avoid grapefruit juice.",
                            MedicationID = "med-ator-20",
                            PrescriptionID = "presc-03",
                            Quantity = 30
                        },
                        new
                        {
                            ItemID = "pi-05",
                            Dosage = "20mg",
                            DoseScheduleJSON = "{\"morning\": 1}",
                            DurationDays = 14,
                            Frequency = "Once daily before breakfast",
                            Indication = "Gastric protection.",
                            Instruction = "Take 30 mins before food.",
                            MedicationID = "med-omep-20",
                            PrescriptionID = "presc-03",
                            Quantity = 14
                        },
                        new
                        {
                            ItemID = "pi-06",
                            Dosage = "400mg",
                            DoseScheduleJSON = "{\"morning\": 1, \"afternoon\": 1, \"evening\": 1, \"night\": 1}",
                            DurationDays = 5,
                            Frequency = "Every 6 hours",
                            Indication = "Pain relief.",
                            Instruction = "Take with food.",
                            MedicationID = "med-ibu-400",
                            PrescriptionID = "presc-04",
                            Quantity = 20
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PrescriptionModel", b =>
                {
                    b.Property<string>("PrescriptionID")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DispensedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PharmacistID")
                        .HasColumnType("text");

                    b.Property<DateTime>("PrescriptionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RecordID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PrescriptionID");

                    b.HasIndex("PharmacistID");

                    b.HasIndex("RecordID")
                        .IsUnique();

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            PrescriptionID = "presc-01",
                            DispensedAt = new DateTime(2025, 12, 6, 10, 6, 37, 939, DateTimeKind.Utc).AddTicks(9130),
                            PrescriptionDateTime = new DateTime(2025, 12, 5, 19, 36, 37, 939, DateTimeKind.Utc).AddTicks(9124),
                            Priority = 0,
                            RecordID = "rec-01",
                            Status = 0,
                            VerifiedAt = new DateTime(2025, 12, 6, 10, 6, 37, 939, DateTimeKind.Utc).AddTicks(9126)
                        },
                        new
                        {
                            PrescriptionID = "presc-02",
                            DispensedAt = new DateTime(2025, 12, 5, 1, 51, 37, 939, DateTimeKind.Utc).AddTicks(9134),
                            PharmacistID = "phar-01",
                            PrescriptionDateTime = new DateTime(2025, 12, 5, 1, 6, 37, 939, DateTimeKind.Utc).AddTicks(9132),
                            Priority = 0,
                            RecordID = "rec-02",
                            Status = 1,
                            VerifiedAt = new DateTime(2025, 12, 5, 1, 36, 37, 939, DateTimeKind.Utc).AddTicks(9133)
                        },
                        new
                        {
                            PrescriptionID = "presc-03",
                            DispensedAt = new DateTime(2025, 12, 1, 21, 36, 37, 939, DateTimeKind.Utc).AddTicks(9138),
                            PharmacistID = "phar-02",
                            PrescriptionDateTime = new DateTime(2025, 12, 1, 21, 6, 37, 939, DateTimeKind.Utc).AddTicks(9136),
                            Priority = 1,
                            RecordID = "rec-03",
                            Status = 1,
                            VerifiedAt = new DateTime(2025, 12, 1, 21, 21, 37, 939, DateTimeKind.Utc).AddTicks(9137)
                        },
                        new
                        {
                            PrescriptionID = "presc-04",
                            DispensedAt = new DateTime(2025, 12, 6, 10, 6, 37, 939, DateTimeKind.Utc).AddTicks(9143),
                            PrescriptionDateTime = new DateTime(2025, 11, 27, 1, 36, 37, 939, DateTimeKind.Utc).AddTicks(9141),
                            Priority = 2,
                            RecordID = "rec-04",
                            Status = 3,
                            VerifiedAt = new DateTime(2025, 11, 27, 2, 6, 37, 939, DateTimeKind.Utc).AddTicks(9142)
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.UserModel", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = "user-pat-01",
                            Email = "john@example.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            PasswordHash = "Password123!",
                            PhoneNumber = "0901234567",
                            Role = 0,
                            Username = "john.doe"
                        },
                        new
                        {
                            UserID = "user-doc-01",
                            Email = "sarah.smith@clinic.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Smith",
                            PasswordHash = "Password123!",
                            PhoneNumber = "0909998887",
                            Role = 1,
                            Username = "dr.sarah"
                        },
                        new
                        {
                            UserID = "user-phar-01",
                            Email = "david.chen@pharmacy.com",
                            FirstName = "David",
                            IsActive = true,
                            LastName = "Chen",
                            PasswordHash = "Password123!",
                            PhoneNumber = "0905554443",
                            Role = 2,
                            Username = "phar.david"
                        },
                        new
                        {
                            UserID = "user-pat-02",
                            Email = "alice.b@example.com",
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Brown",
                            PasswordHash = "Password123!",
                            PhoneNumber = "0908887776",
                            Role = 0,
                            Username = "alice.brown"
                        },
                        new
                        {
                            UserID = "user-doc-02",
                            Email = "james.wilson@clinic.com",
                            FirstName = "James",
                            IsActive = true,
                            LastName = "Wilson",
                            PasswordHash = "Password123!",
                            PhoneNumber = "0901112223",
                            Role = 1,
                            Username = "dr.james"
                        },
                        new
                        {
                            UserID = "user-pat-03",
                            Email = "mike.j@example.com",
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Jordan",
                            PasswordHash = "Password123!",
                            PhoneNumber = "0901122334",
                            Role = 0,
                            Username = "mike.j"
                        },
                        new
                        {
                            UserID = "user-pat-04",
                            Email = "emily.c@example.com",
                            FirstName = "Emily",
                            IsActive = true,
                            LastName = "Clark",
                            PasswordHash = "Password123!",
                            PhoneNumber = "0909988776",
                            Role = 0,
                            Username = "emily.c"
                        },
                        new
                        {
                            UserID = "user-doc-03",
                            Email = "house@clinic.com",
                            FirstName = "Gregory",
                            IsActive = true,
                            LastName = "House",
                            PasswordHash = "Password123!",
                            PhoneNumber = "0906666666",
                            Role = 1,
                            Username = "dr.house"
                        },
                        new
                        {
                            UserID = "user-doc-04",
                            Email = "grey@clinic.com",
                            FirstName = "Meredith",
                            IsActive = true,
                            LastName = "Grey",
                            PasswordHash = "Password123!",
                            PhoneNumber = "0907777777",
                            Role = 1,
                            Username = "dr.grey"
                        },
                        new
                        {
                            UserID = "user-phar-02",
                            Email = "lisa.w@pharmacy.com",
                            FirstName = "Lisa",
                            IsActive = true,
                            LastName = "Wong",
                            PasswordHash = "Password123!",
                            PhoneNumber = "0904443332",
                            Role = 2,
                            Username = "phar.lisa"
                        });
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.AppointmentModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.DoctorModel", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.PatientModel", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.ClinicalExaminationModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.MedicalRecordModel", "MedicalRecord")
                        .WithOne("ClinicalExamination")
                        .HasForeignKey("PersonalizedHealthcareTrackingSystemFinal.Models.ClinicalExaminationModel", "RecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.DoctorModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.UserModel", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("PersonalizedHealthcareTrackingSystemFinal.Models.DoctorModel", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.DoctorScheduleModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.DoctorModel", "Doctor")
                        .WithMany("DoctorSchedules")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicalRecordModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.AppointmentModel", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("PersonalizedHealthcareTrackingSystemFinal.Models.MedicalRecordModel", "AppointmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationInteractionModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationModel", "Medication1")
                        .WithMany("MedicationInteractions1")
                        .HasForeignKey("Medication1ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationModel", "Medication2")
                        .WithMany("MedicationInteractions2")
                        .HasForeignKey("Medication2ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medication1");

                    b.Navigation("Medication2");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationStockLogModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationModel", "Medication")
                        .WithMany("MedicationStockLogs")
                        .HasForeignKey("MedicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.PrescriptionModel", "Prescription")
                        .WithMany("MedicationStockLogs")
                        .HasForeignKey("RelatedPrescriptionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Medication");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PatientModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.UserModel", "User")
                        .WithOne("Patient")
                        .HasForeignKey("PersonalizedHealthcareTrackingSystemFinal.Models.PatientModel", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PharmacistModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.UserModel", "User")
                        .WithOne("Pharmacist")
                        .HasForeignKey("PersonalizedHealthcareTrackingSystemFinal.Models.PharmacistModel", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PrescriptionItemModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationModel", "Medication")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("MedicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.PrescriptionModel", "Prescription")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("PrescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PrescriptionModel", b =>
                {
                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.PharmacistModel", "PharmacistChecking")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PharmacistID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PersonalizedHealthcareTrackingSystemFinal.Models.MedicalRecordModel", "MedicalRecord")
                        .WithOne("Prescription")
                        .HasForeignKey("PersonalizedHealthcareTrackingSystemFinal.Models.PrescriptionModel", "RecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");

                    b.Navigation("PharmacistChecking");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.AppointmentModel", b =>
                {
                    b.Navigation("MedicalRecord")
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.DoctorModel", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorSchedules");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicalRecordModel", b =>
                {
                    b.Navigation("ClinicalExamination")
                        .IsRequired();

                    b.Navigation("Prescription")
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.MedicationModel", b =>
                {
                    b.Navigation("MedicationInteractions1");

                    b.Navigation("MedicationInteractions2");

                    b.Navigation("MedicationStockLogs");

                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PatientModel", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PharmacistModel", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.PrescriptionModel", b =>
                {
                    b.Navigation("MedicationStockLogs");

                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("PersonalizedHealthcareTrackingSystemFinal.Models.UserModel", b =>
                {
                    b.Navigation("Doctor")
                        .IsRequired();

                    b.Navigation("Patient")
                        .IsRequired();

                    b.Navigation("Pharmacist")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
